HW1
inspired99/software-design-2022-itmo-spr pull request #2
Opened 2022-04-18 10:43 UTC by inspired99

2022-04-18 10:43 UTC, inspired99 commented
Сразу забыл открыть PR(

2022-06-06 09:34 UTC, FirstTimeInForever requested changes
Так получилось что про вас я узнал только сегодня, поэтому прошу прощения что только ссейчас проверяю. Если будете что-то исправлять пишите мне напрямую в тг.

* Какой-то треш с модулями: 
```
software-design-2022-itmo-spr $ python Bash/src/main.py
Traceback (most recent call last):
  File "/home/ivm/stuff/ifmo-sd/software-design-2022-itmo-spr/Bash/src/main.py", line 1, in <module>
    from src.bash.bash import CommandLine
ModuleNotFoundError: No module named 'src'
software-design-2022-itmo-spr $ cd Bash          
Bash $ python src/main.py 
Traceback (most recent call last):
  File "/home/ivm/stuff/ifmo-sd/software-design-2022-itmo-spr/Bash/src/main.py", line 1, in <module>
    from src.bash.bash import CommandLine
ModuleNotFoundError: No module named 'src'
```
`-1`.

* Инструкция по запуску, соответственно, не работает. `-0.5`.

* Не работают внешние команды:
```
ls
Command not found: ls
du
Command not found: du
top
Command not found: top
vi
Command not found: vi
```
`-1`.

* Не обрабатывается пайп в пустоту (ожидается ошибка или поведение как в баше):
```
cat .gitignore |
```
`-0.5`.

* Не обрабатываются несбалансированные кавычки (ожидается ошибка или поведение как в баше):
```
echo "
```
`-0.5`.

* Было бы неплохо иметь адекватный `.editorconfig`
* Очень советую использовать `venv` для проектов больше 1-2 файлов.

`6.5/10`.

2022-06-06 09:34 UTC, FirstTimeInForever commented on Bash/src/commandInterface/command.py
> +    command_list = ['cat', 'wc', 'pwd', 'echo', 'exit']
Зачем это тут?

2022-06-06 09:34 UTC, FirstTimeInForever commented on Bash/src/bash/bash.py
> +        self.external_commands = {'vim': ExternalCommand,
А что если я хочу запустить не `vim`, а `vi`? Шелл ничего не должен знать про внешние команды. Нужно исправить.

2022-06-06 09:34 UTC, FirstTimeInForever commented on Bash/src/commandInterface/command.py
> +    @staticmethod
Почему `@staticmethod`?

2022-06-06 09:34 UTC, FirstTimeInForever commented on Bash/src/commandInterface/command.py
> +    from_pipeline = False
Не понятно почему эти поля по-факту статические. Из-за этих полей у вас получается зависимость на глобальное состояние. А что если захочется запустить два ваших баша параллельно?

2022-06-06 09:34 UTC, FirstTimeInForever commented on Bash/src/commandInterface/exitCommand.py
> +        return sys.exit('Command Line is terminated. Goodbye!')
Это не даст выполниться вызывающему коду, который __всегда__ ожидает возвращаения ему управления. Можно, например, пропустить освождение каких-то ресурсов. Надо `exit` как-то по-другому заимплементить.

2022-06-13 13:15 UTC, inspired99 commented on Bash/src/commandInterface/command.py
> +    @staticmethod
На момент реализации показалось, что  так удобнее, чтобы каждый раз не создавать новый инстанс для каждой команды.

2022-06-13 13:15 UTC, inspired99 commented on Bash/src/commandInterface/command.py
> +    from_pipeline = False
Да, они действителньно статические и кажется это не совсем удачное решение

2022-06-14 17:19 UTC, inspired99 commented on Bash/src/commandInterface/command.py
> +    command_list = ['cat', 'wc', 'pwd', 'echo', 'exit']
Действительно, убрал

2022-06-14 21:36 UTC, inspired99 commented on Bash/src/commandInterface/exitCommand.py
> +        return sys.exit('Command Line is terminated. Goodbye!')
Ввел exit_status

2022-06-15 01:01 UTC, inspired99 commented on Bash/src/bash/bash.py
> +        self.external_commands = {'vim': ExternalCommand,
Исправил

2022-06-15 21:51 UTC, closed without merging